Bug fixes
GoogleCloudDataproc/dataproc-jupyter-plugin pull request #142
Opened 2024-04-26 16:40 UTC by Shubha-accenture

1. Implemented server side pagination
2. Pagination changes for fetching first and last page
3. Vertical spacing for Dataset explorer (Schema and Preview)

2024-04-27 00:02 UTC, ojarjur reviewed
Looks good on the Python front, but we need someone else to review the Typescript changes before merging.

2024-04-30 16:24 UTC, ojarjur commented on dataproc_jupyter_plugin/utils/utils.py
We should not have any files named just `utils`. That's never going to be the right name to for a package in this repo.

2024-05-06 16:09 UTC, ojarjur commented on dataproc_jupyter_plugin/utils/credentials.py
Please rename this to `dataproc_juptyer_plugin/credentials.py`.

There's no reason to have anything in the codebase named `utils`.

2024-05-09 13:14 UTC, harsha-accenture commented on dataproc_jupyter_plugin/utils/credentials.py
1. credentials.py is renamed to gcloudOperations.py
2. utils folder is renamed to commons as it contains all the common code.

2024-05-09 16:13 UTC, ptwng approved these changes

2024-05-09 16:13 UTC, ptwng commented on src/bigQuery/previewDataInfo.tsx
> +const previewHeight = window.innerHeight - 180;
this wouldn't work if the user resizes the browser after js was loaded

2024-05-09 16:16 UTC, ptwng commented
Just the one thing around statically grabbing the window width

2024-05-09 16:17 UTC, ptwng requested changes
Just the one thing around statically grabbing the screen width

2024-05-09 16:25 UTC, ojarjur reviewed
The Python changes are fine, so this can be merged once Pat approves the TS changes

2024-05-17 18:57 UTC, ptwng approved these changes

2024-05-20 17:59 UTC, merged